#!/bin/sh
#$ -V
#$ -cwd
#$ -S /bin/bash
#$ -N baeolophus_l_spades
#$ -o $JOB_NAME.o$JOB_ID
#$ -e $JOB_NAME.e$JOB_ID
#$ -q omni
#$ -pe sm 24
#$ -P quanah
#$ -l h_rt=48:00:00
#$ -l h_vmem=8G

spades.py --rna --pe1-1 /lustre/scratch/johruska/Baeolophus_RNA/01_filtered_data/B_bicolor_L_LHD1272_R1.fastq.gz \
--pe1-2 /lustre/scratch/johruska/Baeolophus_RNA/01_filtered_data/B_bicolor_L_LHD1272_R2.fastq.gz \
--pe2-1 /lustre/scratch/johruska/Baeolophus_RNA/01_filtered_data/B_bicolor_L_LHD1279_R1.fastq.gz \
--pe2-2 /lustre/scratch/johruska/Baeolophus_RNA/01_filtered_data/B_bicolor_L_LHD1279_R2.fastq.gz \
--pe3-1 /lustre/scratch/johruska/Baeolophus_RNA/01_filtered_data/B_bicolor_L_LHD1280_R1.fastq.gz \
--pe3-2 /lustre/scratch/johruska/Baeolophus_RNA/01_filtered_data/B_bicolor_L_LHD1280_R2.fastq.gz \
-o /lustre/scratch/johruska/Baeolophus_RNA/baeolophus_l_spades_output --phred-offset 33 -t 24 -m 192
